### ISSUE TITLE
Fix Pandas SQLAlchemy data type issues and resolve warnings

### ISSUE THREAD

**Issue by sbadithe** [alteryx/featuretools_sql#39]
Pandas's IO library is throwing warnings when we use it with a non-SQLAlchemy connector object. Furthermore, there seems to be issues with snowflake.connector objects handling particular data types. 

We should decide how we want to resolve this issue, either by working around it or switching to SQLAlchemy.

**Comment by gsheni** [comment]
@sbadithe is this now fixed, since we use SQLAlchemy?

**Comment by sbadithe** [comment]
@gsheni This issue can be closed after we switch `psycopg2` to `sqlalchemy`. I can do that now, before releasing v3.0.0
